# image
image: Visual Studio 2019

# build platform
platform: x86

# clone directory
clone_folder: c:\HuaweiBootloader-Bruteforce

build:
  project: HuaweiBootloader_Bruteforce.sln
  
build_script:
  - cd c:\HuaweiBootloader-Bruteforce
  - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" HuaweiBootloader_Bruteforce.sln -t:Build -p:Configuration=Release
  
after_build:
- ps: | # package artifacts
    7z a -m0=LZMA2 -mx9 c:\HuaweiBootloader-Bruteforce\HuaweiBootloader-Bruteforce.7z c:\HuaweiBootloader-Bruteforce\bin\Release\*
artifacts:
- path: HuaweiBootloader-Bruteforce.7z
  name: HuaweiBootloader-Bruteforce
